// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Settings(arg1, arg2) {
  return window['go']['Settings']['App']['Settings'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['Settings']['App']['Startup'](arg1);
}
