// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check_now_is_latest(arg1, arg2) {
  return window['go']['Settings']['App']['Check_now_is_latest'](arg1, arg2);
}

export function Get_latest_version_code() {
  return window['go']['Settings']['App']['Get_latest_version_code']();
}

export function Settings(arg1, arg2) {
  return window['go']['Settings']['App']['Settings'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['Settings']['App']['Startup'](arg1);
}
